disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - nesting
  - line_length
  - force_try
  - redundant_optional_initialization
opt_in_rules:
  - empty_count
included:
  - EmeraldComponents
  - EmeraldComponentsTests
  - EmeraldComponentsApplication
excluded:
  - fastlane
  - Pods
  - build

identifier_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
