language: swift

osx_image: xcode10

xcode_workspace: EmeraldComponents.xcworkspace
xcode_scheme: EmeraldComponents

before_install:
  - gem install cocoapods
  - pod repo update
  # - brew install sonar-scanner
  - brew install swiftlint

script:
  - fastlane run_tests_pipeline
