# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EmeraldComponentsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmeraldComponentsApp
  pod 'EmeraldComponents', :path => '..'
#  pod 'SimulatorStatusMagic', '2.2', :configurations => ['Debug']

  target 'EmeraldComponentsAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
