# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

default_platform(:ios)

platform :ios do

	desc "Run tests"
	lane :test do
        install_cocoapods
		lint
		scan(
			scheme: "EmeraldComponents", 
			devices: "iPhone 8",
			code_coverage: true,
			clean: true
		)
		coverage
	end

	desc "Deploy a new version"
    lane :release do
        test
        pod_spec_lint
        release_changelog
        release_github
        release_cocoapods
    end

    desc "set target to get version number"
    lane :projet_version do
        get_version_number(
            target: "EmeraldComponents"
        )
    end

    desc "release new github version"
    lane :release_github do 
        github_release = set_github_release(
            repository_name: "stone-payments/emerald-components-ios",
            api_token: ENV["GITHUB_API_TOKEN"],
            name: "[Deploy 🚀] Release new version - v#{projet_version}",
            tag_name: "#{projet_version}",
            description: (File.read("./CHANGELOG.md") rescue "No changelog provided"),
            commitish: "master"
        )
    end

    desc "Cocoapods linter"
    lane :pod_spec_lint do 
        pod_lib_lint(
            verbose: true,
            allow_warnings: true,
            fail_fast: true
        )
    end

    desc "Do git push"
    lane :release_cocoapods do
        version_podspec
        pod_publish     
    end

    desc "Increment or set the version in a podspec file"
    lane :version_podspec do
        version = version_bump_podspec(path: "EmeraldComponents.podspec", version_number: "#{projet_version}")
        increment_version_number(
            version_number: "#{projet_version}",
            xcodeproj: "./EmeraldComponents.xcodeproj"
        )
    end

    desc "Push podfile"
    lane :pod_publish do 
        pod_push(
            path: "EmeraldComponents.podspec",
            repo: "stone-payments",
            allow_warnings: true,
            verbose: true
        )
    end

    desc "Create release changelog"
    lane :release_changelog do
        v2_changelog = generate_release_changelog(
            github_project: "stone-payments/emerald-components-ios",
            github_api_token: ENV["GITHUB_API_TOKEN"],
            base_branch: "master",
            template_path: "fastlane/changelog_template.erb",
            tag_a: "v#{projet_version}",
            output_path: "CHANGELOG.md"
        )
    end

    desc ""
    lane :install_cocoapods do
        cocoapods(
            podfile: "./EmeraldComponents"
        )
    end

	desc "Run swiftlint"
	lane :lint do
		swiftlint(
		    mode: :lint,
		    output_file: "swiftlint.result.json",
		    reporter: "json",
			config_file: ".swiftlint-ci.yml",
			ignore_exit_status: false
		)
	end

	desc "Get coverage percentage, remove framework's coverage and generate HTML page with coverage data"
	lane :coverage do 
		xcov(
			workspace: "EmeraldComponents.xcworkspace",
  			scheme: "EmeraldComponents",
		 	output_directory: "xcov_output",
            exclude_targets: "JTAppleCalendar.framework, 
                              InputMask.framework",
            minimum_coverage_percentage: 80.0
        )
    end

	desc "Increment minor version"
	lane :increment_version_minor do
	    increment_version_number(bump_type: "minor")
	end

	desc "Increment path version"
	lane :increment_version_patch do
	    increment_version_number(bump_type: "patch")
	end

	desc "Increment version number"
	lane :increment_version do
	    increment_version_number
	end

	desc "Increment custom version"
	lane :increment_version_custom do
		increment_version_number(version_number: "0.1.0")
	end

	desc "Increment build"
	lane :increment_build do
		increment_build_number
	end

end
