# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

import "Pipelines/TestsFastfile"
import "Pipelines/DeployFastfile"

default_platform(:ios)

platform :ios do

    desc "Run tests"
    lane :test do
        slack_start_build
    	run_tests_pipeline
    end

	desc "Deploy a new version"
    lane :release do
        slack_start_build
        run_deploy_pipeline
    end

    desc "Send message to slack that indicates the process has been started"
    lane :slack_start_build do
        slack(
            # author_name: "Author name",
            # author_link: "https://github.com",
            # author_icon: "https://platform.slack-edge.com/img/default_application_icon.png",
            # title: "Pull Request title",
            # title_link: "https://github.com",
            # text: "Pull Request description",
            # color: "#008952",
            channel: "#fastlane",
            slack_url: ENV["SLACK_WEBHOOK"],
            default_payloads: [],
            attachment_properties: {
                fields: [{
                    title: "Project",
                    value: "Emerald iOS",
                    short: true
                }, {
                    title: "Pipeline",
                    value: "Test",
                    short: true
                }],
                # actions: [{
                #     type: "button",
                #     text: "View Pipeline",
                #     url: ENV["BITRISE_Pipeline_URL"]
                # }],
                actions: [{
                    type: "button",
                    text: "View Build",
                    url: ENV["BITRISE_BUILD_URL"]
                }, {
                    type: "button",
                    text: "View Build",
                    url: ENV["BITRISE_BUILD_URL"]
                }, {
                    type: "button",
                    text: "Page Url",
                    url: ENV["BITRISE_PUBLIC_INSTALL_PAGE_URL"]
                }, {
                    type: "button",
                    text: "Page Url map",
                    url: ENV["BITRISE_PUBLIC_INSTALL_PAGE_URL_MAP"]
                }],
                footer: "Bitrise",
                footer_icon: "https://github.com/bitrise-io.png"
            }
        )
    end

end
