# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  	"iPhone 8",
  	"iPhone X"
])

# A list of languages which should be used
# languages([
#   	"en-US",
#   	["pt", "pt_BR"]
# ])

# The name of the scheme which contains the UI Tests
scheme("EmeraldComponentsApp")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Don't open the HTML summary after running snapshot
skip_open_summary(true)

# Should the project be cleaned before building it?
clean(true)

# Should snapshot stop immediately after the tests completely failed on one device?	
stop_after_first_error(true)
